package com.webapp.tracker.finance.model;

/*Here Jakarta Persistence Layer (JPL) is being used instead of Java Persistence API (JPA)
 * They both provide robust frameworks for managing relational data in Java applications and offer similar functionality,
 * but the primary difference is the change of package names.
 * 
 * 
 */
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Pattern;
import lombok.Data;

@Data
@Entity
@Table(name="users")
public class User {
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@Column(unique = true)
	private String username;
	
	@Column(unique = true) 
	@Email(message = "Please provide a valid email address")  //validation for email
	private String email;
	
	@Pattern(regexp = "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$",
			message = "Password must be at least 8 characters and include both letters and numbers")   //validation for password
	private String password;
	
	// Constructors, getters, setters, and other methods can be generated by Lombok

	

}
